# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui',
# licensing of 'ui_mainwindow.ui' applies.
#
# Created: Wed Nov 27 16:57:14 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 567)
        MainWindow.setStyleSheet("QLabel\n"
"{\n"
"font:  20px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"font: 20px\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color:#888888;\n"
"}\n"
"\n"
"#leftPanel\n"
"{\n"
"border: 1px solid;\n"
"}\n"
"\n"
"#middlePanel_2\n"
"{\n"
"border: 1px solid;\n"
"}\n"
"\n"
"#rightPanel\n"
"{\n"
"border: 1px solid;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame[frameShape=\"5\"]\n"
"{\n"
"    border: none;\n"
"    background: grey;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setLineWidth(10)
        self.label_10.setMidLineWidth(3)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/image/logo.jpg"))
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setMargin(0)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.middlePanel_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middlePanel_2.sizePolicy().hasHeightForWidth())
        self.middlePanel_2.setSizePolicy(sizePolicy)
        self.middlePanel_2.setMinimumSize(QtCore.QSize(200, 170))
        self.middlePanel_2.setStyleSheet("")
        self.middlePanel_2.setObjectName("middlePanel_2")
        self.middlePanel = QtWidgets.QVBoxLayout(self.middlePanel_2)
        self.middlePanel.setContentsMargins(0, 0, 0, 0)
        self.middlePanel.setObjectName("middlePanel")
        self.label_6 = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 30px")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.middlePanel.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.middlePanel.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.orderIDLabel = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.orderIDLabel.setFont(font)
        self.orderIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.orderIDLabel.setObjectName("orderIDLabel")
        self.horizontalLayout_4.addWidget(self.orderIDLabel)
        self.middlePanel.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(204, 0, 0);\n"
"")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.numRedLabel = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.numRedLabel.setFont(font)
        self.numRedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numRedLabel.setObjectName("numRedLabel")
        self.horizontalLayout_8.addWidget(self.numRedLabel)
        self.middlePanel.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(237, 212, 0);\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.numYellowLabel = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.numYellowLabel.setFont(font)
        self.numYellowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numYellowLabel.setObjectName("numYellowLabel")
        self.horizontalLayout_10.addWidget(self.numYellowLabel)
        self.middlePanel.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet("color: rgb(32, 74, 135);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.numBlueLabel = QtWidgets.QLabel(self.middlePanel_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.numBlueLabel.setFont(font)
        self.numBlueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numBlueLabel.setObjectName("numBlueLabel")
        self.horizontalLayout_9.addWidget(self.numBlueLabel)
        self.middlePanel.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.middlePanel.addItem(spacerItem1)
        self.horizontalLayout_12.addWidget(self.middlePanel_2)
        self.rightPanel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPanel.sizePolicy().hasHeightForWidth())
        self.rightPanel.setSizePolicy(sizePolicy)
        self.rightPanel.setMinimumSize(QtCore.QSize(200, 170))
        self.rightPanel.setStyleSheet("")
        self.rightPanel.setObjectName("rightPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightPanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 30px\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.qualityLabel = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.qualityLabel.setFont(font)
        self.qualityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qualityLabel.setObjectName("qualityLabel")
        self.horizontalLayout_7.addWidget(self.qualityLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.performanceLabel = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.performanceLabel.setFont(font)
        self.performanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.performanceLabel.setObjectName("performanceLabel")
        self.horizontalLayout_6.addWidget(self.performanceLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.availabilityLabel = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.availabilityLabel.setFont(font)
        self.availabilityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.availabilityLabel.setObjectName("availabilityLabel")
        self.horizontalLayout_5.addWidget(self.availabilityLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_12.addWidget(self.rightPanel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 30px")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(100, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"alignment: AlignHLeft\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_2.addWidget(self.statusLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(100, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.packmlStateLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packmlStateLabel.sizePolicy().hasHeightForWidth())
        self.packmlStateLabel.setSizePolicy(sizePolicy)
        self.packmlStateLabel.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.packmlStateLabel.setFont(font)
        self.packmlStateLabel.setStyleSheet("")
        self.packmlStateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.packmlStateLabel.setObjectName("packmlStateLabel")
        self.horizontalLayout_3.addWidget(self.packmlStateLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0,0, 0);\n"
"background-color: #00FF00;\n"
"}\n"
"\n"
"")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_15.addWidget(self.startButton)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_15.addWidget(self.resetButton)
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pauseButton.setFont(font)
        self.pauseButton.setStyleSheet("backgrond: black")
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_15.addWidget(self.pauseButton)
        self.abortButton = QtWidgets.QPushButton(self.centralwidget)
        self.abortButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortButton.sizePolicy().hasHeightForWidth())
        self.abortButton.setSizePolicy(sizePolicy)
        self.abortButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.abortButton.setFont(font)
        self.abortButton.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0,0, 0);\n"
"background-color: #FF0000;\n"
"}\n"
"\n"
"")
        self.abortButton.setObjectName("abortButton")
        self.horizontalLayout_15.addWidget(self.abortButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(100, 100))
        self.stopButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_15.addWidget(self.stopButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.horizontalLayout_14)
        self.lightTowerStatus = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(183)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightTowerStatus.sizePolicy().hasHeightForWidth())
        self.lightTowerStatus.setSizePolicy(sizePolicy)
        self.lightTowerStatus.setMinimumSize(QtCore.QSize(183, 281))
        self.lightTowerStatus.setFrameShape(QtWidgets.QFrame.Box)
        self.lightTowerStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lightTowerStatus.setLineWidth(5)
        self.lightTowerStatus.setMidLineWidth(3)
        self.lightTowerStatus.setText("")
        self.lightTowerStatus.setObjectName("lightTowerStatus")
        self.horizontalLayout.addWidget(self.lightTowerStatus)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", " Order status", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Current order ID", None, -1))
        self.orderIDLabel.setText(QtWidgets.QApplication.translate("MainWindow", "1337", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "# Red", None, -1))
        self.numRedLabel.setText(QtWidgets.QApplication.translate("MainWindow", "1/2", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "# Yellow", None, -1))
        self.numYellowLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0/1", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "# Blue", None, -1))
        self.numBlueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "1/5", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", " OEE statistics", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Quality", None, -1))
        self.qualityLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0.65", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Performance", None, -1))
        self.performanceLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0.95", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Availability", None, -1))
        self.availabilityLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0.3", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Uptime", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "02:34:13", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "System control", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Status:", None, -1))
        self.statusLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Picking from feeder", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "PackML state:", None, -1))
        self.packmlStateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Stopped", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.resetButton.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.pauseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Hold", None, -1))
        self.abortButton.setText(QtWidgets.QApplication.translate("MainWindow", "Abort", None, -1))
        self.stopButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))

import resources_rc
