IDLE = ()

GRASP_BLUE = ()
GRASP_RED = ()
GRASP_YELLOW = ()
GRASP_BRICKS = (GRASP_BLUE, GRASP_RED, GRASP_YELLOW)

ABOVE_BLUE = ()
ABOVE_RED = ()
ABOVE_YELLOW = ()
ABOVE_BRICKS = (ABOVE_BLUE, ABOVE_RED, ABOVE_YELLOW)

ABOVE_CAMERA = ()

BRICK_DROP_ORDER_BOX = ()
BRICK_DROP_DISCARD_BOX = ()

ABOVE_ORDER_BOX_EDGE = ()
GRASP_ORDER_BOX_EDGE = ()
ORDER_BOX_DROP_MIR = ()
